export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    darkText: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description : 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
    buttonLabel: 'Get Started',
    imgStart : false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    darkText: true,
    topLine: 'Unlimited Access',
    headline: 'Login to your account at any time',
    description : 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer',
    buttonLabel: 'Learn More',
    imgStart : true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Piggybank',
    dark: false,
    primary: false,
}

// export const homeObjThree = {
//     id: 'signup',
//     lightBg: true,
//     lightText: false,
//     darkText: true,
//     topLine: 'Premium Bank',
//     headline: 'Unlimited Transactions with zero fees',
//     description : 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees',
//     buttonLabel: 'Learn More',
//     imgStart : false,
//     img: require('../../images/svg-3.svg').default,
//     alt: 'Paper',
//     dark: false,
//     primary: false,
// }

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    darkText: true,
    topLine: 'Join our team',
    headline: 'Creating an account is extremely easy',
    description : 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and you\'re ready to go',
    buttonLabel: 'Start Now',
    imgStart : false,
    img: require('../../images/svg-4.svg').default,
    alt: 'Paper',
    dark: false,
    primary: false,
}